// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJRTYNyfX39fUthyyM29EVLveufYn80Rw',
    appId: '1:340378178218:web:b61283fcff71b18c6876d3',
    messagingSenderId: '340378178218',
    projectId: 'e-pass-8ca34',
    authDomain: 'e-pass-8ca34.firebaseapp.com',
    storageBucket: 'e-pass-8ca34.appspot.com',
    measurementId: 'G-W9KTZP76SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR_RzEnLhgRcR7j9vrNOsfxN5oZX4-sxE',
    appId: '1:340378178218:android:7d12cc5eae96da046876d3',
    messagingSenderId: '340378178218',
    projectId: 'e-pass-8ca34',
    storageBucket: 'e-pass-8ca34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMTQNnunCc2o6HbqphC9XnC3343J1asu0',
    appId: '1:340378178218:ios:ce8b668e9631b7636876d3',
    messagingSenderId: '340378178218',
    projectId: 'e-pass-8ca34',
    storageBucket: 'e-pass-8ca34.appspot.com',
    iosClientId:
        '340378178218-6rf666tmiv4ejp67rm019qn21sqcnss2.apps.googleusercontent.com',
    iosBundleId: 'com.ehallpass.eHallPass',
  );
}
